import type { NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";

const Topic: NextPage<{}> = () => {
  return (
    <div className="container">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="page"></main>

      <style jsx>{`
        .page {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: var(--padding);
        }

        .posts-grid {
          display: flex;
          flex-direction: column;
          gap: var(--padding);
        }
        .message {
          margin: var(--padding) 0;
        }
        .breadcrumb-bar {
          background: #fff;
          width: 100%;
          border-radius: var(--border-radius);
          padding: var(--padding-sm) var(--padding);
          border: var(--border);
          box-shadow: var(--box-shadow-lg);
          display: flex;
          justify-content: space-between;
          flex-wrap: wrap;
          line-height: 1.5em;
        }
        .breadcrumb-bar p {
          margin: 0;
        }
        .breadcrumb-bar__topic-name {
          font-weight: 600;
          text-transform: uppercase;
        }
        .breadcrumb-bar__return-link {
          text-decoration: 1px solid underline;
          color: var(--primary-main);
        }
        .breadcrumb-bar__return-link:hover {
          opacity: 0.8;
        }
      `}</style>
    </div>
  );
};

export default Topic;
